"""App-wide constants for the ModularSnapshotETL dashboard."""

import os

DB_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "ModularSnapshotETL.db")
DATASET_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "dataset")
LISTING_FILENAME = "listings.csv.gz"

ROOM_TYPES = ["ALL", "Entire home/apt", "Private room", "Shared room", "Hotel room"]

DASHBOARD_URL = "https://modularsnapshotetl.streamlit.app/"

# ---------------------------------------------------------------------------
# Full city catalog for the searchable dropdown (self-contained, no imports).
# Sorted alphabetically by label. Each entry: (slug, label).
# Kept in sync with src/data_fetcher.CITY_CATALOG.
# ---------------------------------------------------------------------------
CITY_OPTIONS: list[tuple[str, str]] = [
    ("amsterdam",          "Amsterdam, Netherlands"),
    ("antwerp",            "Antwerp, Belgium"),
    ("asheville",          "Asheville, US"),
    ("athens",             "Athens, Greece"),
    ("auckland",           "Auckland, NZ"),
    ("austin",             "Austin, US"),
    ("bangkok",            "Bangkok, Thailand"),
    ("barcelona",          "Barcelona, Spain"),
    ("barossa-valley",     "Barossa Valley, Australia"),
    ("euskadi",            "Basque Country, Spain"),
    ("beijing",            "Beijing, China"),
    ("bergen",             "Bergen, Norway"),
    ("bergamo",            "Bergamo, Italy"),
    ("berlin",             "Berlin, Germany"),
    ("bologna",            "Bologna, Italy"),
    ("bordeaux",           "Bordeaux, France"),
    ("boston",              "Boston, US"),
    ("bristol",            "Bristol, UK"),
    ("brussels",           "Brussels, Belgium"),
    ("buenos-aires",       "Buenos Aires, Argentina"),
    ("cambridge",          "Cambridge, US"),
    ("cape-town",          "Cape Town, South Africa"),
    ("chicago",            "Chicago, US"),
    ("cleveland",          "Cleveland, US"),
    ("columbus",           "Columbus, US"),
    ("copenhagen",         "Copenhagen, Denmark"),
    ("crete",              "Crete, Greece"),
    ("dallas",             "Dallas, US"),
    ("denver",             "Denver, US"),
    ("dublin",             "Dublin, Ireland"),
    ("edinburgh",          "Edinburgh, UK"),
    ("florence",           "Florence, Italy"),
    ("fort-worth",         "Fort Worth, US"),
    ("geneva",             "Geneva, Switzerland"),
    ("girona",             "Girona, Spain"),
    ("glasgow",            "Glasgow, UK"),
    ("havana",             "Havana, Cuba"),
    ("hawaii",             "Hawaii, US"),
    ("hong-kong",          "Hong Kong, China"),
    ("istanbul",           "Istanbul, Turkey"),
    ("jersey-city",        "Jersey City, US"),
    ("lisbon",             "Lisbon, Portugal"),
    ("london",             "London, UK"),
    ("los-angeles",        "Los Angeles, US"),
    ("lyon",               "Lyon, France"),
    ("madrid",             "Madrid, Spain"),
    ("malaga",             "Malaga, Spain"),
    ("mallorca",           "Mallorca, Spain"),
    ("manchester",         "Manchester, UK"),
    ("medellin",           "Medellin, Colombia"),
    ("melbourne",          "Melbourne, Australia"),
    ("menorca",            "Menorca, Spain"),
    ("mexico-city",        "Mexico City, Mexico"),
    ("milan",              "Milan, Italy"),
    ("minneapolis",        "Minneapolis, US"),
    ("montreal",           "Montreal, Canada"),
    ("munich",             "Munich, Germany"),
    ("naples",             "Naples, Italy"),
    ("nashville",          "Nashville, US"),
    ("new-brunswick",      "New Brunswick, Canada"),
    ("new-orleans",        "New Orleans, US"),
    ("new-york-city",      "New York City, US"),
    ("newark",             "Newark, US"),
    ("northern-rivers",    "Northern Rivers, Australia"),
    ("oakland",            "Oakland, US"),
    ("oslo",               "Oslo, Norway"),
    ("ottawa",             "Ottawa, Canada"),
    ("pacific-grove",      "Pacific Grove, US"),
    ("paris",              "Paris, France"),
    ("porto",              "Porto, Portugal"),
    ("portland",           "Portland, US"),
    ("prague",             "Prague, Czech Republic"),
    ("puglia",             "Puglia, Italy"),
    ("quebec-city",        "Quebec City, Canada"),
    ("rhode-island",       "Rhode Island, US"),
    ("rio-de-janeiro",     "Rio de Janeiro, Brazil"),
    ("rochester",          "Rochester, US"),
    ("rome",               "Rome, Italy"),
    ("salem",              "Salem, US"),
    ("san-diego",          "San Diego, US"),
    ("san-francisco",      "San Francisco, US"),
    ("san-mateo-county",   "San Mateo County, US"),
    ("santa-clara-county", "Santa Clara County, US"),
    ("santa-cruz-county",  "Santa Cruz County, US"),
    ("sardinia",           "Sardinia, Italy"),
    ("seattle",            "Seattle, US"),
    ("sevilla",            "Sevilla, Spain"),
    ("shanghai",           "Shanghai, China"),
    ("sicily",             "Sicily, Italy"),
    ("singapore",          "Singapore"),
    ("south-aegean",       "South Aegean, Greece"),
    ("stockholm",          "Stockholm, Sweden"),
    ("sydney",             "Sydney, Australia"),
    ("tasmania",           "Tasmania, Australia"),
    ("thessaloniki",       "Thessaloniki, Greece"),
    ("tokyo",              "Tokyo, Japan"),
    ("toronto",            "Toronto, Canada"),
    ("saint-paul",         "Twin Cities MSA, US"),
    ("valencia",           "Valencia, Spain"),
    ("vancouver",          "Vancouver, Canada"),
    ("venice",             "Venice, Italy"),
    ("victoria",           "Victoria, Canada"),
    ("vienna",             "Vienna, Austria"),
    ("washington-dc",      "Washington D.C., US"),
    ("western-australia",  "Western Australia"),
    ("winnipeg",           "Winnipeg, Canada"),
    ("zurich",             "Zurich, Switzerland"),
]
